<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                'marca' => 'Toyota',
                'modelo' => 'Corolla',
                'anio' => 2020,
                'kilometraje' => 15000,
                'potencia' => 132,
                'cilindrada' => 1800,
                'combustible' => 'Gasolina',
                'transmision' => 'Automática',
                'color' => 'Blanco',
                'tipo' => 'Sedán',
                'estado' => 'KM 0',
                'ubicacion' => 'Madrid',
                'descripcion' => 'Toyota Corolla 2020 en excelente estado, único dueño, mantenimiento al día.',
                'num_puertas' => 4,
                'num_asientos' => 5,
                'precio' => 18500.00,
                'imagen' => 'images/cars/D3fG7hJ1kL6pQ0rT5vN2bC8sM4wY9xAaZeUo.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 1
            ],
            [
                'marca' => 'Ford',
                'modelo' => 'Focus',
                'anio' => 2020,
                'kilometraje' => 20000,
                'potencia' => 150,
                'cilindrada' => 2000,
                'combustible' => 'Diésel',
                'transmision' => 'Manual',
                'color' => 'Azul',
                'tipo' => 'Hatchback',
                'estado' => 'Segunda Mano',
                'ubicacion' => 'Barcelona',
                'descripcion' => 'Ford Focus 2020, bien cuidado, ideal para ciudad y carretera.',
                'num_puertas' => 5,
                'num_asientos' => 5,
                'precio' => 14500.50,
                'imagen' => 'images/cars/M4kH8pQ1tYvL6xW3sN9bR0jF2gC5zA7uDqEoX.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 2
            ],
            [
                'marca' => 'Tesla',
                'modelo' => 'Model 3',
                'anio' => 2022,
                'kilometraje' => 5000,
                'potencia' => 283,
                'cilindrada' => 0,
                'combustible' => 'Eléctrico (EV)',
                'transmision' => 'Automática',
                'color' => 'blanco',
                'tipo' => 'Sedán',
                'estado' => 'Nuevo',
                'ubicacion' => 'Valencia',
                'descripcion' => 'Tesla Model 3 2022, nuevo, con todas las características de última generación.',
                'num_puertas' => 4,
                'num_asientos' => 5,
                'precio' => 38999.99,
                'imagen' => 'images/cars/Z8xC2vB5nM1qW4eR7tY3uI0oP6aS9dFjKhlG.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 3
            ],
            [
                'marca' => 'BMW',
                'modelo' => 'Serie 3',
                'anio' => 2019,
                'kilometraje' => 30000,
                'potencia' => 255,
                'cilindrada' => 2000,
                'combustible' => 'Gasolina',
                'transmision' => 'Automática',
                'color' => 'blanco',
                'tipo' => 'Sedán',
                'estado' => 'KM 0',
                'ubicacion' => 'Sevilla',
                'descripcion' => 'BMW Serie 3 2019, deportivo y elegante, perfecto para quienes buscan rendimiento y estilo.',
                'num_puertas' => 4,
                'num_asientos' => 5,
                'precio' => 27500.00,
                'imagen' => 'images/cars/aD9Kf3VbX7zLqT1yP6mH4cJ8rN0wGvR5sQ2eFZ.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 4
            ],
            [
                'marca' => 'Kia',
                'modelo' => 'Sportage',
                'anio' => 2021,
                'kilometraje' => 10000,
                'potencia' => 181,
                'cilindrada' => 1600,
                'combustible' => 'Gasolina',
                'transmision' => 'Automática',
                'color' => 'Rojo',
                'tipo' => 'SUV',
                'estado' => 'Segunda Mano',
                'ubicacion' => 'Bilbao',
                'descripcion' => 'Kia Sportage 2021, espacioso y cómodo, ideal para familias y aventuras.',
                'num_puertas' => 5,
                'num_asientos' => 5,
                'precio' => 22000.00,
                'imagen' => 'images/cars/F1rV8yZ3cN5mH2tJ6wP9kX0qL4bG7sAeDdUo.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 5
            ],
            [
                'marca' => 'Audi',
                'modelo' => 'A4',
                'anio' => 2018,
                'kilometraje' => 40000,
                'potencia' => 190,
                'cilindrada' => 2000,
                'combustible' => 'Gasolina',
                'transmision' => 'Automática',
                'color' => 'Negro',
                'tipo' => 'Sedán',
                'estado' => 'KM 0',
                'ubicacion' => 'Zaragoza',
                'descripcion' => 'Audi A4 2018, elegante y potente, perfecto para viajes largos.',
                'num_puertas' => 4,
                'num_asientos' => 5,
                'precio' => 21000.00,
                'imagen' => 'images/cars/G7kL2aP9fWq8HjV4xZs1N6rTbYdQ0CmXvF3wAeK.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 6
            ],
            [
                'marca' => 'Volkswagen',
                'modelo' => 'Golf',
                'anio' => 2017,
                'kilometraje' => 50000,
                'potencia' => 115,
                'cilindrada' => 1600,
                'combustible' => 'Diésel',
                'transmision' => 'Manual',
                'color' => 'Gris',
                'tipo' => 'Hatchback',
                'estado' => 'Segunda Mano',
                'ubicacion' => 'Granada',
                'descripcion' => 'Volkswagen Golf 2017, económico y fiable, ideal para ciudad.',
                'num_puertas' => 5,
                'num_asientos' => 5,
                'precio' => 13500.00,
                'imagen' => 'images/cars/yP6kH2wR9sL4vT7mJ1cF0bG3nQ8zAeXdUoEe.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 7
            ],
            [
                'marca' => 'Mercedes-Benz',
                'modelo' => 'Clase C',
                'anio' => 2021,
                'kilometraje' => 8000,
                'potencia' => 204,
                'cilindrada' => 2000,
                'combustible' => 'Gasolina',
                'transmision' => 'Automática',
                'color' => 'Plateado',
                'tipo' => 'Sedán',
                'estado' => 'Nuevo',
                'ubicacion' => 'Valencia',
                'descripcion' => 'Mercedes-Benz Clase C 2021, lujo y tecnología de última generación.',
                'num_puertas' => 4,
                'num_asientos' => 5,
                'precio' => 42000.00,
                'imagen' => 'images/cars/X6hN2pT7wL9vR1fC5kY4sQ8mB0jG3zAaUdEe.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 8
            ],
            [
                'marca' => 'Renault',
                'modelo' => 'Clio',
                'anio' => 2016,
                'kilometraje' => 60000,
                'potencia' => 90,
                'cilindrada' => 1200,
                'combustible' => 'Gasolina',
                'transmision' => 'Manual',
                'color' => 'Amarillo',
                'tipo' => 'Hatchback',
                'estado' => 'KM 0',
                'ubicacion' => 'Alicante',
                'descripcion' => 'Renault Clio 2016, compacto y práctico, perfecto para jóvenes.',
                'num_puertas' => 5,
                'num_asientos' => 5,
                'precio' => 8900.00,
                'imagen' => 'images/cars/L5kJ9vN2pQ4xH7sT1fG6bR0cM3wY8zAeDdUo.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 9
            ],
            [
                'marca' => 'Peugeot',
                'modelo' => '3008',
                'anio' => 2019,
                'kilometraje' => 25000,
                'potencia' => 130,
                'cilindrada' => 1500,
                'combustible' => 'Diésel',
                'transmision' => 'Automática',
                'color' => 'Verde',
                'tipo' => 'SUV',
                'estado' => 'Segunda Mano',
                'ubicacion' => 'Santander',
                'descripcion' => 'Peugeot 3008 2019, SUV moderno y espacioso, ideal para familias.',
                'num_puertas' => 5,
                'num_asientos' => 5,
                'precio' => 23500.00,
                'imagen' => 'images/cars/qW3rE7tY1uI9oP2aS4dF6gH8jK0lZ5xCvBnM.webp',
                'created_at' => now(),
                'updated_at' => now(),
                'propietario' => 10
            ],
        ]);
    }
}
